### ISSUE TITLE
Requesting support for AAVE staking

### ISSUE THREAD

**Issue by mocolicious** [enzymefinance/protocol#1043]
AAVE staking would add another avenue of investing for vault managers by providing security for the safety protocol in AAVE and receiving the incentives provided.  The APIs for AAVE can allow tracking of these amounts.

**Comment by SeanJCasey** [comment]
Thanks for the issue, will investigate!

**Comment by SeanJCasey** [comment]
Submitted an AIP to make this possible in Enzyme: https://governance.aave.com/t/proposal-adapt-contracts-slightly-to-improve-defi-composability/4125
