### ISSUE TITLE
Requesting support to redeem stAave for lending 

### ISSUE THREAD

**Issue by mocolicious** [enzymefinance/protocol#1045]
This is a new feature that was added this week but AAVE now rewards stAave (staked AAVE) for borrowing or lending certain coins.  So any fund that is lending Dai, ETH, WBTC, etc. right now is also being rewarded with stAave that they can claim.

**Comment by SeanJCasey** [comment]
@mocolicious Thanks for creating this issue. We're already on it, but it will likely require a core change because of how the claiming functions are implemented. For now, the rewards will accumulate to your VaultProxy, but will not be claimable until a subsequent release.

**Comment by mocolicious** [comment]
@SeanJCasey thanks for the update!  I look forward to the subsequent release.  will be a game changer for vault managers.

**Comment by SeanJCasey** [comment]
Submitted an AIP to make this possible in Enzyme: https://governance.aave.com/t/proposal-adapt-contracts-slightly-to-improve-defi-composability/4125

**Comment by devbest555** [comment]
const denominationAsset = new WETH(config.weth, whales.weth);
I got error from it when I test

what should I do with config.weth, whales.weth address?
for example, should I add them in my metamask?
Please help me.
