### ISSUE TITLE
Unable to deploy contracts  in kovan testnet

### ISSUE THREAD

**Issue by vinodionixx** [enzymefinance/protocol#1047]
![enzyme-error](https://user-images.githubusercontent.com/89623777/132222800-d2acd598-5c45-4dae-b2b1-f485bcf63743.png)

**Comment by devbest555** [comment]
please reply here so I can lead you.

**Comment by vinodionixx** [comment]
I'm trying to deploy an enzymefinance protocol in the Kovan test network.
Here are my observations:
Able to deploy a few contracts.
While deploying ChainLinkPriceFeed its throwing ProviderError: The execution failed due to an exception.
Because of this undeployment,  unable to deploy other contracts.
Tried deploying the contracts to ropsten test network but issue remains same.
When i go through the error i can see the error is regarding Estimate gas issue or UNPREDICTABLE GAS.

**Comment by devbest555** [comment]
> I'm trying to deploy an enzymefinance protocol in the Kovan test network.
> Here are my observations:
> Able to deploy a few contracts.
> While deploying ChainLinkPriceFeed its throwing ProviderError: The execution failed due to an exception.
> Because of this undeployment, unable to deploy other contracts.
> Tried deploying the contracts to ropsten test network but issue remains same.
> When i go through the error i can see the error is regarding Estimate gas issue or UNPREDICTABLE GAS.

it is not gas problem.
it is enzyme protocol error.

**Comment by vinodionixx** [comment]
@devbest555 is there any fix or turn around ?

**Comment by devbest555** [comment]
please contact me in the telegram.

**Comment by dennohpeter** [comment]
@vinodionixx  did you find a fix/solution for this?

**Comment by vinodionixx** [comment]
@dennohpeter  not yet.

**Comment by eakarsu** [comment]
Did you find any solution on this?

**Comment by SeanJCasey** [comment]
For questions and support, please use our Discord discord.enzyme.finance
