### ISSUE TITLE
Re installing on kovan

### ISSUE THREAD

**Issue by eakarsu** [enzymefinance/protocol#1050]
I could not install enzyme on kovan network. Can you help us? I face first problem Config module is not installed. I have changed Mainnet.ts fd.skip function. Then installation was stuck at deploying ValueInterpreter. I think chainlink data is not valid. Can you help me on how I can install on kovan or any testnet? I appreciate your help.

deploying "ValueInterpreter" (tx: 0xd533db60bb5d0e30240c48ec05ca9ad133d997797a972072f8a760b93eb39c36)...: deployed at 0x35451c0188f570222E14287EB871E9DFD4249892 with 2413125 gas
An unexpected error occurred:

Error: ERROR processing /tmp/files/deploy/scripts/release/infrastructure/ValueInterpreter.ts:
ProviderError: The execution failed due to an exception.

**Comment by SeanJCasey** [comment]
For questions and support, please use our Discord discord.enzyme.finance
